import { createHash } from 'node:crypto'

import { and, eq } from 'drizzle-orm'

import { getDb } from '@/db'
import { prayerGenerationUploads } from '@/db/schema'
import { getMediaStorage } from '@/providers/media/storage'
import {
  checkObjectStorageAllowed,
  getObjectStorage,
  resolveObjectStorage,
} from '@/providers/object-storage/registry'
import { ObjectStorageError } from '@/providers/object-storage/types'
import {
  DEFAULT_LEASE_MS,
  GenerationJobError,
  claimNextUploadJob,
  isLegalTransition,
  renewGenerationLease,
  sanitizeErrorMessage,
  scheduleRetryOrFail,
  transitionGenerationJobUnderLease,
} from './generation-jobs'
import { verifyCompletedRender } from './render-assembly'
import type { RenderContext } from './render-assembly'
import type { GenerationClock } from './generation-jobs'
import type { ObjectStorageProvider } from '@/providers/object-storage/types'

/**
 * Private object-storage upload (Phase One, Step 17).
 *
 * ```text
 * UPLOADING job
 * → re-prove the EXACT Step 16 render/result/current authority
 *   (verifyCompletedRender — the SAME proof Step 16's own gate runs)
 * → place the verified local bytes at a SERVER-GENERATED canonical
 *   PRIVATE object key, or reuse the identical object already there
 * → re-prove the remote object against the exact local artifact
 * → READY
 * ```
 *
 * READY means the generation pipeline's artifact is complete and
 * PRIVATELY stored. Step 17 creates NO Prayer Room, exposes NO media,
 * publishes nothing, and hands no URL — signed or otherwise — to
 * anybody. A signed read URL is never generated by this pipeline,
 * never persisted and never logged.
 */

// --- Identity ---------------------------------------------------------------

/** Extensions a finished render may be stored under — bounded, and
 * kept in step with the render engine's own output allowlist. */
const UPLOAD_MIME_EXTENSIONS: Record<string, string> = {
  'video/mp4': 'mp4',
  'video/webm': 'webm',
}

/**
 * Deterministic upload identity. The SAME render result always maps to
 * the SAME upload and therefore the SAME canonical object, which is
 * exactly what makes a crash-interrupted upload recoverable: a retry
 * finds the object it already wrote instead of writing a second one.
 */
export function computeUploadIdempotencyKey(input: {
  generationJobId: number
  renderResultId: number
  renderPlanSha256: string
  artifactSha256: string
}): string {
  return createHash('sha256')
    .update(
      `upload-v1|${input.generationJobId}|${input.renderResultId}|${input.renderPlanSha256}|${input.artifactSha256}`,
      'utf8',
    )
    .digest('hex')
}

/**
 * The canonical destination key, derived ONLY from the opaque
 * idempotency hash.
 *
 * Nothing a person could recognise goes into an object path: no
 * appointment reference, no user or house or service name, no theme, no
 * language, no timestamp, and nothing a user ever typed. A storage
 * listing is therefore not a list of who prayed for what.
 */
export function buildCanonicalObjectKey(
  idempotencyKey: string,
  mimeType: string,
): { ok: true; objectKey: string } | { ok: false; reasonCode: string } {
  const extension = UPLOAD_MIME_EXTENSIONS[mimeType]
  if (!extension) return { ok: false, reasonCode: 'artifact_mime_invalid' }
  if (!/^[0-9a-f]{64}$/.test(idempotencyKey)) {
    return { ok: false, reasonCode: 'idempotency_key_invalid' }
  }
  return {
    ok: true,
    objectKey: `renders/${idempotencyKey.slice(0, 2)}/${idempotencyKey}.${extension}`,
  }
}

// --- Persistence ------------------------------------------------------------

async function ensureUploadRow(input: {
  generationJobId: number
  renderResultId: number
  renderPlanSnapshotId: number
  renderPlanSha256: string
  idempotencyKey: string
  objectKey: string
  artifactSha256: string
  artifactMimeType: string
  artifactDurationMs: number
  byteSize: number
  provider: Pick<ObjectStorageProvider, 'code' | 'isLocal'>
}): Promise<typeof prayerGenerationUploads.$inferSelect> {
  const db = getDb()
  const find = async () =>
    (
      await db
        .select()
        .from(prayerGenerationUploads)
        .where(
          and(
            eq(prayerGenerationUploads.generationJobId, input.generationJobId),
            eq(prayerGenerationUploads.renderResultId, input.renderResultId),
          ),
        )
        .limit(1)
    ).at(0)
  const existing = await find()
  if (existing) return existing
  try {
    await db.insert(prayerGenerationUploads).values({
      generationJobId: input.generationJobId,
      renderResultId: input.renderResultId,
      renderPlanSnapshotId: input.renderPlanSnapshotId,
      renderPlanSha256: input.renderPlanSha256,
      idempotencyKey: input.idempotencyKey,
      providerCode: input.provider.code,
      providerIsLocal: input.provider.isLocal ? 1 : 0,
      objectKey: input.objectKey,
      artifactSha256: input.artifactSha256,
      artifactMimeType: input.artifactMimeType,
      artifactDurationMs: input.artifactDurationMs,
      byteSize: input.byteSize,
      status: 'PENDING',
    })
  } catch {
    // A duplicate insert just means another worker created it first.
  }
  const row = await find()
  if (!row) throw new GenerationJobError('Upload row vanished after insert.')
  return row
}

export type UploadOutcome =
  | { status: 'IDLE' }
  | { status: 'COMPLETE'; jobId: number }
  | { status: 'RETRY_SCHEDULED'; jobId: number; errorCode: string }
  | { status: 'FAILED'; jobId: number; errorCode: string }
  | { status: 'LEASE_LOST'; jobId: number }

export interface UploadDependencies {
  /** Injectable ONLY so a test can model a slow or failing provider
   * call; the default is the registry's active provider. */
  putPrivateObject?: ObjectStorageProvider['putPrivateObject']
}

/**
 * One upload cycle: claim an UPLOADING (or resuming RETRYING) job,
 * re-prove the entire Step 16 result, place the verified bytes at the
 * canonical private key (or adopt the identical object already there),
 * re-prove the remote object, then finalize UPLOADING → READY behind a
 * full second proof.
 *
 * CRASH SAFETY. Because the key is canonical, "the object already
 * exists" is the NORMAL recovery case, not an error: a worker that
 * uploaded successfully and died before writing the database finds its
 * own object on retry, verifies it, and records success without a
 * second accepted upload. An object at the canonical key whose bytes
 * DIFFER is a different matter entirely and fails closed — it is never
 * overwritten.
 *
 * For the same reason a stale worker NEVER deletes the canonical
 * object: unlike a render artifact (whose key is freshly minted per
 * attempt), this key is shared by every attempt, so deleting it after
 * losing a database race would destroy another worker's valid upload.
 */
export async function runUploadOnce(
  workerId: string,
  clock: GenerationClock,
  dependencies: UploadDependencies = {},
): Promise<UploadOutcome> {
  const claimed = await claimNextUploadJob(workerId, clock)
  if (!claimed) return { status: 'IDLE' }
  const { job, leaseToken } = claimed
  const attempt = job.attemptCount + 1

  const heartbeat = async (): Promise<boolean> =>
    renewGenerationLease(job.id, leaseToken, clock)
  // An upload can be long-running: keep renewing throughout.
  const heartbeatTimer = setInterval(
    () => {
      void renewGenerationLease(job.id, leaseToken, clock).catch(
        () => undefined,
      )
    },
    Math.max(1_000, Math.floor(DEFAULT_LEASE_MS / 3)),
  )

  const fail = async (
    code: string,
    detail: string | null,
  ): Promise<UploadOutcome> => {
    const outcome = await scheduleRetryOrFail(
      job,
      leaseToken,
      clock,
      code,
      detail,
      'UPLOADING',
    )
    if (outcome === 'LOST') return { status: 'LEASE_LOST', jobId: job.id }
    return outcome === 'FAILED'
      ? { status: 'FAILED', jobId: job.id, errorCode: code }
      : { status: 'RETRY_SCHEDULED', jobId: job.id, errorCode: code }
  }

  try {
    if (job.status === 'RETRYING') {
      const resumed = await transitionGenerationJobUnderLease(
        job.id,
        leaseToken,
        'RETRYING',
        'UPLOADING',
        clock,
        {
          eventCode: 'upload_resumed',
          attemptNumber: attempt,
          patch: { resumeStatus: null },
        },
      )
      if (!resumed) return { status: 'LEASE_LOST', jobId: job.id }
    }
    if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }

    const context: RenderContext = {
      serviceId: job.serviceIdSnapshot,
      sacredHouseId: job.sacredHouseIdSnapshot,
      language: job.languageSnapshot,
    }

    // The SAME proof Step 16's own gate runs — re-run from scratch, not
    // trusted from the row that said RENDERING was finished.
    const render = await verifyCompletedRender(job.id, context)
    if (!render.ok) return fail(render.errorCode, render.detail)
    const { plan, result, planSnapshotId } = render.verified

    const provider = getObjectStorage()
    const allowed = checkObjectStorageAllowed(provider)
    if (!allowed.ok) return fail('OBJECT_STORAGE_NOT_PERMITTED', allowed.reasonCode)

    const idempotencyKey = computeUploadIdempotencyKey({
      generationJobId: job.id,
      renderResultId: result.id,
      renderPlanSha256: result.renderPlanSha256,
      artifactSha256: result.artifactSha256!,
    })
    const canonical = buildCanonicalObjectKey(
      idempotencyKey,
      result.artifactMimeType!,
    )
    if (!canonical.ok) return fail('UPLOAD_IDENTITY_INVALID', canonical.reasonCode)

    // The exact local bytes verifyCompletedRender just proved.
    const localBytes = await getMediaStorage().get(result.artifactStorageRef!)
    if (!localBytes || localBytes.length === 0) {
      return fail('RENDER_ARTIFACT_INVALID', 'local_artifact_missing')
    }

    const row = await ensureUploadRow({
      generationJobId: job.id,
      renderResultId: result.id,
      renderPlanSnapshotId: planSnapshotId,
      renderPlanSha256: result.renderPlanSha256,
      idempotencyKey,
      objectKey: canonical.objectKey,
      artifactSha256: result.artifactSha256!,
      artifactMimeType: result.artifactMimeType!,
      artifactDurationMs: result.artifactDurationMs!,
      byteSize: localBytes.length,
      provider,
    })

    // IDENTITY BEFORE SPEND. The row we are about to upload for must BE
    // this job's upload for this render result, at this canonical key,
    // for these exact bytes. A disagreement means the row was altered
    // after it was created, and uploading against it would attach a
    // stranger's object to this appointment.
    const identityFailure =
      row.generationJobId !== job.id
        ? 'upload_job_mismatch'
        : row.renderResultId !== result.id
          ? 'upload_result_mismatch'
          : row.renderPlanSnapshotId !== planSnapshotId
            ? 'upload_plan_snapshot_mismatch'
            : row.renderPlanSha256 !== result.renderPlanSha256
              ? 'upload_plan_hash_mismatch'
              : row.idempotencyKey !== idempotencyKey
                ? 'upload_idempotency_mismatch'
                : row.objectKey !== canonical.objectKey
                  ? 'upload_object_key_mismatch'
                  : row.artifactSha256 !== result.artifactSha256
                    ? 'upload_artifact_hash_mismatch'
                    : row.artifactMimeType !== result.artifactMimeType
                      ? 'upload_artifact_mime_mismatch'
                      : row.artifactDurationMs !== result.artifactDurationMs
                        ? 'upload_artifact_duration_mismatch'
                        : row.byteSize !== localBytes.length
                          ? 'upload_byte_size_mismatch'
                          : null
    if (identityFailure != null) {
      return fail('UPLOAD_IDENTITY_MISMATCH', identityFailure)
    }
    if (row.artifactMimeType !== plan.outputMimeType) {
      return fail('UPLOAD_IDENTITY_MISMATCH', 'upload_plan_mime_mismatch')
    }
    if (row.artifactDurationMs !== plan.totalDurationMs) {
      return fail('UPLOAD_IDENTITY_MISMATCH', 'upload_plan_duration_mismatch')
    }

    if (row.status !== 'SUCCEEDED') {
      const statusAtRead = row.status
      const started = await getDb()
        .update(prayerGenerationUploads)
        .set({
          status: 'UPLOADING',
          attemptCount: row.attemptCount + 1,
          startedAt: clock.now(),
          lastErrorCode: null,
          lastErrorMessage: null,
        })
        .where(
          and(
            eq(prayerGenerationUploads.id, row.id),
            eq(prayerGenerationUploads.status, statusAtRead),
          ),
        )
      if (started[0].affectedRows !== 1) {
        // Another worker owns this upload right now — never race it.
        return fail('UPLOAD_ALREADY_RUNNING', null)
      }

      if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }
      let descriptor
      try {
        // CRASH RECOVERY: is our canonical object already there?
        const head = await provider.headPrivateObject(canonical.objectKey)
        if (head) {
          const existing = await provider.verifyPrivateObjectIntegrity({
            objectKey: canonical.objectKey,
            expectedSha256: row.artifactSha256,
            expectedByteSize: row.byteSize,
            expectedMimeType: row.artifactMimeType,
          })
          if (!existing.ok) {
            // Something else is at OUR canonical key. It is never
            // overwritten: whatever it is, destroying it is not this
            // stage's decision to make.
            return fail(
              'UPLOAD_OBJECT_CONFLICT',
              `canonical_object_differs:${existing.reasonCode}`.slice(0, 500),
            )
          }
          // Byte-identical: adopt it. This is the normal recovery from
          // "uploaded, then crashed before the database write".
          descriptor = existing.descriptor
        } else {
          const put = dependencies.putPrivateObject
            ? await dependencies.putPrivateObject({
                objectKey: canonical.objectKey,
                bytes: localBytes,
                mimeType: row.artifactMimeType,
                sha256: row.artifactSha256,
              })
            : await provider.putPrivateObject({
                objectKey: canonical.objectKey,
                bytes: localBytes,
                mimeType: row.artifactMimeType,
                sha256: row.artifactSha256,
              })
          descriptor = put
        }
      } catch (error) {
        const code =
          error instanceof ObjectStorageError ? error.code : 'upload_failed'
        // STALE FAILURE FENCE: a worker that lost its lease records
        // nothing — the newer owner may legitimately be mid-upload on
        // this very row, and the status CAS alone cannot tell us apart.
        if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }
        await getDb()
          .update(prayerGenerationUploads)
          .set({
            status: 'FAILED',
            lastErrorCode: code.slice(0, 60),
            lastErrorMessage: sanitizeErrorMessage(error),
            completedAt: clock.now(),
          })
          .where(
            and(
              eq(prayerGenerationUploads.id, row.id),
              eq(prayerGenerationUploads.status, 'UPLOADING'),
            ),
          )
        return fail('UPLOAD_FAILED', code.slice(0, 500))
      }

      // The provider said yes; that is not proof. NOTE: from here on a
      // rejection must NOT delete the object — the key is canonical and
      // shared by every attempt, so deleting it could destroy another
      // worker's valid upload.
      if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }
      const remote = await provider.verifyPrivateObjectIntegrity({
        objectKey: canonical.objectKey,
        expectedSha256: row.artifactSha256,
        expectedByteSize: row.byteSize,
        expectedMimeType: row.artifactMimeType,
      })
      if (!remote.ok) {
        if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }
        await getDb()
          .update(prayerGenerationUploads)
          .set({
            status: 'FAILED',
            lastErrorCode: remote.reasonCode.slice(0, 60),
            completedAt: clock.now(),
          })
          .where(
            and(
              eq(prayerGenerationUploads.id, row.id),
              eq(prayerGenerationUploads.status, 'UPLOADING'),
            ),
          )
        return fail('UPLOAD_REMOTE_INTEGRITY_FAILURE', remote.reasonCode)
      }

      if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }
      const accepted = await getDb()
        .update(prayerGenerationUploads)
        .set({
          status: 'SUCCEEDED',
          providerCode: provider.code,
          providerIsLocal: provider.isLocal ? 1 : 0,
          // Opaque bookkeeping only — never treated as a content hash.
          providerEtag: descriptor.providerEtag?.slice(0, 200) ?? null,
          providerVersionId: descriptor.providerVersionId?.slice(0, 200) ?? null,
          lastErrorCode: null,
          lastErrorMessage: null,
          completedAt: clock.now(),
        })
        .where(
          and(
            eq(prayerGenerationUploads.id, row.id),
            eq(prayerGenerationUploads.status, 'UPLOADING'),
          ),
        )
      if (accepted[0].affectedRows !== 1) {
        // Someone else resolved this row while we uploaded. The object
        // is canonical and identical, so it stays exactly where it is.
        return fail('UPLOAD_RESULT_SUPERSEDED', null)
      }
    }

    // --- FINAL GATE ---------------------------------------------------
    if (!(await heartbeat())) return { status: 'LEASE_LOST', jobId: job.id }

    const revalidatedRender = await verifyCompletedRender(job.id, context, {
      renderResultId: result.id,
      planSnapshotId,
    })
    if (!revalidatedRender.ok) {
      return fail(revalidatedRender.errorCode, revalidatedRender.detail)
    }

    const finalRow = (
      await getDb()
        .select()
        .from(prayerGenerationUploads)
        .where(eq(prayerGenerationUploads.id, row.id))
        .limit(1)
    ).at(0)
    if (!finalRow) return fail('UPLOAD_ROW_MISSING', null)
    if (
      finalRow.generationJobId !== job.id ||
      finalRow.renderResultId !== revalidatedRender.verified.result.id ||
      finalRow.renderPlanSha256 !==
        revalidatedRender.verified.result.renderPlanSha256 ||
      finalRow.idempotencyKey !== idempotencyKey ||
      finalRow.objectKey !== canonical.objectKey ||
      finalRow.artifactSha256 !== revalidatedRender.verified.result.artifactSha256
    ) {
      return fail('UPLOAD_IDENTITY_MISMATCH', 'upload_identity_moved')
    }
    if (finalRow.status !== 'SUCCEEDED') {
      return fail('UPLOAD_NOT_SUCCEEDED', finalRow.status)
    }
    // The provider holding this object must still be resolvable and
    // still permitted HERE — a local object can never be walked forward
    // in production, whichever provider happens to be active now.
    const holdingProvider = resolveObjectStorage(finalRow.providerCode)
    if (!holdingProvider) {
      return fail('OBJECT_STORAGE_NOT_PERMITTED', 'provider_code_mismatch')
    }
    const stillAllowed = checkObjectStorageAllowed(holdingProvider)
    if (!stillAllowed.ok) {
      return fail('OBJECT_STORAGE_NOT_PERMITTED', stillAllowed.reasonCode)
    }
    const stillIntact = await holdingProvider.verifyPrivateObjectIntegrity({
      objectKey: finalRow.objectKey,
      expectedSha256: finalRow.artifactSha256,
      expectedByteSize: finalRow.byteSize,
      expectedMimeType: finalRow.artifactMimeType,
    })
    if (!stillIntact.ok) {
      return fail('UPLOAD_REMOTE_INTEGRITY_FAILURE', stillIntact.reasonCode)
    }

    if (!isLegalTransition('UPLOADING', 'READY')) {
      throw new GenerationJobError('Illegal transition UPLOADING → READY.')
    }
    const finalized = await transitionGenerationJobUnderLease(
      job.id,
      leaseToken,
      'UPLOADING',
      'READY',
      clock,
      {
        eventCode: 'upload_complete',
        attemptNumber: attempt,
        clearLease: true,
        patch: {
          attemptCount: attempt,
          lastErrorCode: null,
          lastErrorMessage: null,
          nextAttemptAt: null,
          resumeStatus: null,
        },
      },
    )
    return finalized
      ? { status: 'COMPLETE', jobId: job.id }
      : { status: 'LEASE_LOST', jobId: job.id }
  } catch (error) {
    return fail('UPLOAD_ERROR', sanitizeErrorMessage(error))
  } finally {
    clearInterval(heartbeatTimer)
  }
}
