/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OlodumareRouteImport } from './routes/olodumare'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as AppointmentsPublicIdRouteImport } from './routes/appointments.$publicId'
import { Route as BookServiceSlugRouteImport } from './routes/book.$serviceSlug'
import { Route as CheckoutAppointmentPublicIdRouteImport } from './routes/checkout.$appointmentPublicId'
import { Route as DeitiesIndexRouteImport } from './routes/deities.index'
import { Route as DeitiesSlugRouteImport } from './routes/deities.$slug'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileConsentsRouteImport } from './routes/profile.consents'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileSpiritualRouteImport } from './routes/profile.spiritual'
import { Route as SacredHousesIndexRouteImport } from './routes/sacred-houses.index'
import { Route as SacredHousesSlugRouteImport } from './routes/sacred-houses.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin.appointments.index'
import { Route as AdminAppointmentsIdRouteImport } from './routes/admin.appointments.$id'
import { Route as AdminCatalogueIndexRouteImport } from './routes/admin.catalogue.index'
import { Route as AdminCatalogueReviewRouteImport } from './routes/admin.catalogue.review'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin.payments.$id'
import { Route as AdminPrayerTemplatesIndexRouteImport } from './routes/admin.prayer-templates.index'
import { Route as AdminPrayerTemplatesIdRouteImport } from './routes/admin.prayer-templates.$id'
import { Route as AdminPrayerTemplatesNewRouteImport } from './routes/admin.prayer-templates.new'
import { Route as AdminPrayerTemplatesReviewRouteImport } from './routes/admin.prayer-templates.review'
import { Route as AdminSacredContentIndexRouteImport } from './routes/admin.sacred-content.index'
import { Route as AdminSacredContentIdRouteImport } from './routes/admin.sacred-content.$id'
import { Route as AdminSacredContentNewRouteImport } from './routes/admin.sacred-content.new'
import { Route as AdminSacredContentReviewRouteImport } from './routes/admin.sacred-content.review'
import { Route as AdminSacredContentRuntimeRouteImport } from './routes/admin.sacred-content.runtime'
import { Route as AdminSchedulingIndexRouteImport } from './routes/admin.scheduling.index'
import { Route as AdminSchedulingHouseIdRouteImport } from './routes/admin.scheduling.$houseId'
import { Route as AdminSpiritualContentIndexRouteImport } from './routes/admin.spiritual-content.index'
import { Route as AdminSpiritualContentIdRouteImport } from './routes/admin.spiritual-content.$id'
import { Route as AdminSpiritualContentNewRouteImport } from './routes/admin.spiritual-content.new'
import { Route as AdminSpiritualContentReviewRouteImport } from './routes/admin.spiritual-content.review'
import { Route as ApiWebhooksProviderRouteImport } from './routes/api.webhooks.$provider'
import { Route as PaymentsReceiptAttemptPublicIdRouteImport } from './routes/payments.receipt.$attemptPublicId'
import { Route as PaymentsReturnProviderRouteImport } from './routes/payments.return.$provider'
import { Route as AdminCatalogueDeitiesIndexRouteImport } from './routes/admin.catalogue.deities.index'
import { Route as AdminCatalogueDeitiesIdRouteImport } from './routes/admin.catalogue.deities.$id'
import { Route as AdminCatalogueDeitiesNewRouteImport } from './routes/admin.catalogue.deities.new'
import { Route as AdminCatalogueSacredHousesIndexRouteImport } from './routes/admin.catalogue.sacred-houses.index'
import { Route as AdminCatalogueSacredHousesIdRouteImport } from './routes/admin.catalogue.sacred-houses.$id'
import { Route as AdminCatalogueSacredHousesNewRouteImport } from './routes/admin.catalogue.sacred-houses.new'
import { Route as AdminCatalogueServicesIndexRouteImport } from './routes/admin.catalogue.services.index'
import { Route as AdminCatalogueServicesIdRouteImport } from './routes/admin.catalogue.services.$id'
import { Route as AdminCatalogueServicesNewRouteImport } from './routes/admin.catalogue.services.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OlodumareRoute = OlodumareRouteImport.update({
  id: '/olodumare',
  path: '/olodumare',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsPublicIdRoute = AppointmentsPublicIdRouteImport.update({
  id: '/appointments/$publicId',
  path: '/appointments/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookServiceSlugRoute = BookServiceSlugRouteImport.update({
  id: '/book/$serviceSlug',
  path: '/book/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAppointmentPublicIdRoute =
  CheckoutAppointmentPublicIdRouteImport.update({
    id: '/checkout/$appointmentPublicId',
    path: '/checkout/$appointmentPublicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeitiesIndexRoute = DeitiesIndexRouteImport.update({
  id: '/deities/',
  path: '/deities/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeitiesSlugRoute = DeitiesSlugRouteImport.update({
  id: '/deities/$slug',
  path: '/deities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileConsentsRoute = ProfileConsentsRouteImport.update({
  id: '/profile/consents',
  path: '/profile/consents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSpiritualRoute = ProfileSpiritualRouteImport.update({
  id: '/profile/spiritual',
  path: '/profile/spiritual',
  getParentRoute: () => rootRouteImport,
} as any)
const SacredHousesIndexRoute = SacredHousesIndexRouteImport.update({
  id: '/sacred-houses/',
  path: '/sacred-houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const SacredHousesSlugRoute = SacredHousesSlugRouteImport.update({
  id: '/sacred-houses/$slug',
  path: '/sacred-houses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsIdRoute = AdminAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueIndexRoute = AdminCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueReviewRoute = AdminCatalogueReviewRouteImport.update({
  id: '/catalogue/review',
  path: '/catalogue/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerTemplatesIndexRoute =
  AdminPrayerTemplatesIndexRouteImport.update({
    id: '/prayer-templates/',
    path: '/prayer-templates/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPrayerTemplatesIdRoute = AdminPrayerTemplatesIdRouteImport.update({
  id: '/prayer-templates/$id',
  path: '/prayer-templates/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerTemplatesNewRoute = AdminPrayerTemplatesNewRouteImport.update({
  id: '/prayer-templates/new',
  path: '/prayer-templates/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerTemplatesReviewRoute =
  AdminPrayerTemplatesReviewRouteImport.update({
    id: '/prayer-templates/review',
    path: '/prayer-templates/review',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSacredContentIndexRoute = AdminSacredContentIndexRouteImport.update({
  id: '/sacred-content/',
  path: '/sacred-content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSacredContentIdRoute = AdminSacredContentIdRouteImport.update({
  id: '/sacred-content/$id',
  path: '/sacred-content/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSacredContentNewRoute = AdminSacredContentNewRouteImport.update({
  id: '/sacred-content/new',
  path: '/sacred-content/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSacredContentReviewRoute =
  AdminSacredContentReviewRouteImport.update({
    id: '/sacred-content/review',
    path: '/sacred-content/review',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSacredContentRuntimeRoute =
  AdminSacredContentRuntimeRouteImport.update({
    id: '/sacred-content/runtime',
    path: '/sacred-content/runtime',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSchedulingIndexRoute = AdminSchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulingHouseIdRoute = AdminSchedulingHouseIdRouteImport.update({
  id: '/scheduling/$houseId',
  path: '/scheduling/$houseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpiritualContentIndexRoute =
  AdminSpiritualContentIndexRouteImport.update({
    id: '/spiritual-content/',
    path: '/spiritual-content/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSpiritualContentIdRoute = AdminSpiritualContentIdRouteImport.update({
  id: '/spiritual-content/$id',
  path: '/spiritual-content/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpiritualContentNewRoute =
  AdminSpiritualContentNewRouteImport.update({
    id: '/spiritual-content/new',
    path: '/spiritual-content/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSpiritualContentReviewRoute =
  AdminSpiritualContentReviewRouteImport.update({
    id: '/spiritual-content/review',
    path: '/spiritual-content/review',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiWebhooksProviderRoute = ApiWebhooksProviderRouteImport.update({
  id: '/api/webhooks/$provider',
  path: '/api/webhooks/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsReceiptAttemptPublicIdRoute =
  PaymentsReceiptAttemptPublicIdRouteImport.update({
    id: '/payments/receipt/$attemptPublicId',
    path: '/payments/receipt/$attemptPublicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentsReturnProviderRoute = PaymentsReturnProviderRouteImport.update({
  id: '/payments/return/$provider',
  path: '/payments/return/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogueDeitiesIndexRoute =
  AdminCatalogueDeitiesIndexRouteImport.update({
    id: '/catalogue/deities/',
    path: '/catalogue/deities/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueDeitiesIdRoute = AdminCatalogueDeitiesIdRouteImport.update({
  id: '/catalogue/deities/$id',
  path: '/catalogue/deities/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueDeitiesNewRoute =
  AdminCatalogueDeitiesNewRouteImport.update({
    id: '/catalogue/deities/new',
    path: '/catalogue/deities/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueSacredHousesIndexRoute =
  AdminCatalogueSacredHousesIndexRouteImport.update({
    id: '/catalogue/sacred-houses/',
    path: '/catalogue/sacred-houses/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueSacredHousesIdRoute =
  AdminCatalogueSacredHousesIdRouteImport.update({
    id: '/catalogue/sacred-houses/$id',
    path: '/catalogue/sacred-houses/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueSacredHousesNewRoute =
  AdminCatalogueSacredHousesNewRouteImport.update({
    id: '/catalogue/sacred-houses/new',
    path: '/catalogue/sacred-houses/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueServicesIndexRoute =
  AdminCatalogueServicesIndexRouteImport.update({
    id: '/catalogue/services/',
    path: '/catalogue/services/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueServicesIdRoute =
  AdminCatalogueServicesIdRouteImport.update({
    id: '/catalogue/services/$id',
    path: '/catalogue/services/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueServicesNewRoute =
  AdminCatalogueServicesNewRouteImport.update({
    id: '/catalogue/services/new',
    path: '/catalogue/services/new',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/olodumare': typeof OlodumareRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/appointments/$publicId': typeof AppointmentsPublicIdRoute
  '/book/$serviceSlug': typeof BookServiceSlugRoute
  '/checkout/$appointmentPublicId': typeof CheckoutAppointmentPublicIdRoute
  '/deities/$slug': typeof DeitiesSlugRoute
  '/profile/consents': typeof ProfileConsentsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/spiritual': typeof ProfileSpiritualRoute
  '/sacred-houses/$slug': typeof SacredHousesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/deities/': typeof DeitiesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sacred-houses/': typeof SacredHousesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/catalogue/review': typeof AdminCatalogueReviewRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/prayer-templates/$id': typeof AdminPrayerTemplatesIdRoute
  '/admin/prayer-templates/new': typeof AdminPrayerTemplatesNewRoute
  '/admin/prayer-templates/review': typeof AdminPrayerTemplatesReviewRoute
  '/admin/sacred-content/$id': typeof AdminSacredContentIdRoute
  '/admin/sacred-content/new': typeof AdminSacredContentNewRoute
  '/admin/sacred-content/review': typeof AdminSacredContentReviewRoute
  '/admin/sacred-content/runtime': typeof AdminSacredContentRuntimeRoute
  '/admin/scheduling/$houseId': typeof AdminSchedulingHouseIdRoute
  '/admin/spiritual-content/$id': typeof AdminSpiritualContentIdRoute
  '/admin/spiritual-content/new': typeof AdminSpiritualContentNewRoute
  '/admin/spiritual-content/review': typeof AdminSpiritualContentReviewRoute
  '/api/webhooks/$provider': typeof ApiWebhooksProviderRoute
  '/payments/receipt/$attemptPublicId': typeof PaymentsReceiptAttemptPublicIdRoute
  '/payments/return/$provider': typeof PaymentsReturnProviderRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/catalogue/': typeof AdminCatalogueIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/prayer-templates/': typeof AdminPrayerTemplatesIndexRoute
  '/admin/sacred-content/': typeof AdminSacredContentIndexRoute
  '/admin/scheduling/': typeof AdminSchedulingIndexRoute
  '/admin/spiritual-content/': typeof AdminSpiritualContentIndexRoute
  '/admin/catalogue/deities/$id': typeof AdminCatalogueDeitiesIdRoute
  '/admin/catalogue/deities/new': typeof AdminCatalogueDeitiesNewRoute
  '/admin/catalogue/sacred-houses/$id': typeof AdminCatalogueSacredHousesIdRoute
  '/admin/catalogue/sacred-houses/new': typeof AdminCatalogueSacredHousesNewRoute
  '/admin/catalogue/services/$id': typeof AdminCatalogueServicesIdRoute
  '/admin/catalogue/services/new': typeof AdminCatalogueServicesNewRoute
  '/admin/catalogue/deities/': typeof AdminCatalogueDeitiesIndexRoute
  '/admin/catalogue/sacred-houses/': typeof AdminCatalogueSacredHousesIndexRoute
  '/admin/catalogue/services/': typeof AdminCatalogueServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/olodumare': typeof OlodumareRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/appointments/$publicId': typeof AppointmentsPublicIdRoute
  '/book/$serviceSlug': typeof BookServiceSlugRoute
  '/checkout/$appointmentPublicId': typeof CheckoutAppointmentPublicIdRoute
  '/deities/$slug': typeof DeitiesSlugRoute
  '/profile/consents': typeof ProfileConsentsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/spiritual': typeof ProfileSpiritualRoute
  '/sacred-houses/$slug': typeof SacredHousesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/deities': typeof DeitiesIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/sacred-houses': typeof SacredHousesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/catalogue/review': typeof AdminCatalogueReviewRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/prayer-templates/$id': typeof AdminPrayerTemplatesIdRoute
  '/admin/prayer-templates/new': typeof AdminPrayerTemplatesNewRoute
  '/admin/prayer-templates/review': typeof AdminPrayerTemplatesReviewRoute
  '/admin/sacred-content/$id': typeof AdminSacredContentIdRoute
  '/admin/sacred-content/new': typeof AdminSacredContentNewRoute
  '/admin/sacred-content/review': typeof AdminSacredContentReviewRoute
  '/admin/sacred-content/runtime': typeof AdminSacredContentRuntimeRoute
  '/admin/scheduling/$houseId': typeof AdminSchedulingHouseIdRoute
  '/admin/spiritual-content/$id': typeof AdminSpiritualContentIdRoute
  '/admin/spiritual-content/new': typeof AdminSpiritualContentNewRoute
  '/admin/spiritual-content/review': typeof AdminSpiritualContentReviewRoute
  '/api/webhooks/$provider': typeof ApiWebhooksProviderRoute
  '/payments/receipt/$attemptPublicId': typeof PaymentsReceiptAttemptPublicIdRoute
  '/payments/return/$provider': typeof PaymentsReturnProviderRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/catalogue': typeof AdminCatalogueIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/prayer-templates': typeof AdminPrayerTemplatesIndexRoute
  '/admin/sacred-content': typeof AdminSacredContentIndexRoute
  '/admin/scheduling': typeof AdminSchedulingIndexRoute
  '/admin/spiritual-content': typeof AdminSpiritualContentIndexRoute
  '/admin/catalogue/deities/$id': typeof AdminCatalogueDeitiesIdRoute
  '/admin/catalogue/deities/new': typeof AdminCatalogueDeitiesNewRoute
  '/admin/catalogue/sacred-houses/$id': typeof AdminCatalogueSacredHousesIdRoute
  '/admin/catalogue/sacred-houses/new': typeof AdminCatalogueSacredHousesNewRoute
  '/admin/catalogue/services/$id': typeof AdminCatalogueServicesIdRoute
  '/admin/catalogue/services/new': typeof AdminCatalogueServicesNewRoute
  '/admin/catalogue/deities': typeof AdminCatalogueDeitiesIndexRoute
  '/admin/catalogue/sacred-houses': typeof AdminCatalogueSacredHousesIndexRoute
  '/admin/catalogue/services': typeof AdminCatalogueServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/olodumare': typeof OlodumareRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/appointments/$publicId': typeof AppointmentsPublicIdRoute
  '/book/$serviceSlug': typeof BookServiceSlugRoute
  '/checkout/$appointmentPublicId': typeof CheckoutAppointmentPublicIdRoute
  '/deities/$slug': typeof DeitiesSlugRoute
  '/profile/consents': typeof ProfileConsentsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/spiritual': typeof ProfileSpiritualRoute
  '/sacred-houses/$slug': typeof SacredHousesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/deities/': typeof DeitiesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sacred-houses/': typeof SacredHousesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/catalogue/review': typeof AdminCatalogueReviewRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/prayer-templates/$id': typeof AdminPrayerTemplatesIdRoute
  '/admin/prayer-templates/new': typeof AdminPrayerTemplatesNewRoute
  '/admin/prayer-templates/review': typeof AdminPrayerTemplatesReviewRoute
  '/admin/sacred-content/$id': typeof AdminSacredContentIdRoute
  '/admin/sacred-content/new': typeof AdminSacredContentNewRoute
  '/admin/sacred-content/review': typeof AdminSacredContentReviewRoute
  '/admin/sacred-content/runtime': typeof AdminSacredContentRuntimeRoute
  '/admin/scheduling/$houseId': typeof AdminSchedulingHouseIdRoute
  '/admin/spiritual-content/$id': typeof AdminSpiritualContentIdRoute
  '/admin/spiritual-content/new': typeof AdminSpiritualContentNewRoute
  '/admin/spiritual-content/review': typeof AdminSpiritualContentReviewRoute
  '/api/webhooks/$provider': typeof ApiWebhooksProviderRoute
  '/payments/receipt/$attemptPublicId': typeof PaymentsReceiptAttemptPublicIdRoute
  '/payments/return/$provider': typeof PaymentsReturnProviderRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/catalogue/': typeof AdminCatalogueIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/prayer-templates/': typeof AdminPrayerTemplatesIndexRoute
  '/admin/sacred-content/': typeof AdminSacredContentIndexRoute
  '/admin/scheduling/': typeof AdminSchedulingIndexRoute
  '/admin/spiritual-content/': typeof AdminSpiritualContentIndexRoute
  '/admin/catalogue/deities/$id': typeof AdminCatalogueDeitiesIdRoute
  '/admin/catalogue/deities/new': typeof AdminCatalogueDeitiesNewRoute
  '/admin/catalogue/sacred-houses/$id': typeof AdminCatalogueSacredHousesIdRoute
  '/admin/catalogue/sacred-houses/new': typeof AdminCatalogueSacredHousesNewRoute
  '/admin/catalogue/services/$id': typeof AdminCatalogueServicesIdRoute
  '/admin/catalogue/services/new': typeof AdminCatalogueServicesNewRoute
  '/admin/catalogue/deities/': typeof AdminCatalogueDeitiesIndexRoute
  '/admin/catalogue/sacred-houses/': typeof AdminCatalogueSacredHousesIndexRoute
  '/admin/catalogue/services/': typeof AdminCatalogueServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/olodumare'
    | '/register'
    | '/api/health'
    | '/appointments/$publicId'
    | '/book/$serviceSlug'
    | '/checkout/$appointmentPublicId'
    | '/deities/$slug'
    | '/profile/consents'
    | '/profile/edit'
    | '/profile/spiritual'
    | '/sacred-houses/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/appointments/'
    | '/deities/'
    | '/payments/'
    | '/profile/'
    | '/sacred-houses/'
    | '/services/'
    | '/admin/appointments/$id'
    | '/admin/catalogue/review'
    | '/admin/payments/$id'
    | '/admin/prayer-templates/$id'
    | '/admin/prayer-templates/new'
    | '/admin/prayer-templates/review'
    | '/admin/sacred-content/$id'
    | '/admin/sacred-content/new'
    | '/admin/sacred-content/review'
    | '/admin/sacred-content/runtime'
    | '/admin/scheduling/$houseId'
    | '/admin/spiritual-content/$id'
    | '/admin/spiritual-content/new'
    | '/admin/spiritual-content/review'
    | '/api/webhooks/$provider'
    | '/payments/receipt/$attemptPublicId'
    | '/payments/return/$provider'
    | '/admin/appointments/'
    | '/admin/catalogue/'
    | '/admin/payments/'
    | '/admin/prayer-templates/'
    | '/admin/sacred-content/'
    | '/admin/scheduling/'
    | '/admin/spiritual-content/'
    | '/admin/catalogue/deities/$id'
    | '/admin/catalogue/deities/new'
    | '/admin/catalogue/sacred-houses/$id'
    | '/admin/catalogue/sacred-houses/new'
    | '/admin/catalogue/services/$id'
    | '/admin/catalogue/services/new'
    | '/admin/catalogue/deities/'
    | '/admin/catalogue/sacred-houses/'
    | '/admin/catalogue/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/olodumare'
    | '/register'
    | '/api/health'
    | '/appointments/$publicId'
    | '/book/$serviceSlug'
    | '/checkout/$appointmentPublicId'
    | '/deities/$slug'
    | '/profile/consents'
    | '/profile/edit'
    | '/profile/spiritual'
    | '/sacred-houses/$slug'
    | '/services/$slug'
    | '/admin'
    | '/appointments'
    | '/deities'
    | '/payments'
    | '/profile'
    | '/sacred-houses'
    | '/services'
    | '/admin/appointments/$id'
    | '/admin/catalogue/review'
    | '/admin/payments/$id'
    | '/admin/prayer-templates/$id'
    | '/admin/prayer-templates/new'
    | '/admin/prayer-templates/review'
    | '/admin/sacred-content/$id'
    | '/admin/sacred-content/new'
    | '/admin/sacred-content/review'
    | '/admin/sacred-content/runtime'
    | '/admin/scheduling/$houseId'
    | '/admin/spiritual-content/$id'
    | '/admin/spiritual-content/new'
    | '/admin/spiritual-content/review'
    | '/api/webhooks/$provider'
    | '/payments/receipt/$attemptPublicId'
    | '/payments/return/$provider'
    | '/admin/appointments'
    | '/admin/catalogue'
    | '/admin/payments'
    | '/admin/prayer-templates'
    | '/admin/sacred-content'
    | '/admin/scheduling'
    | '/admin/spiritual-content'
    | '/admin/catalogue/deities/$id'
    | '/admin/catalogue/deities/new'
    | '/admin/catalogue/sacred-houses/$id'
    | '/admin/catalogue/sacred-houses/new'
    | '/admin/catalogue/services/$id'
    | '/admin/catalogue/services/new'
    | '/admin/catalogue/deities'
    | '/admin/catalogue/sacred-houses'
    | '/admin/catalogue/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/olodumare'
    | '/register'
    | '/api/health'
    | '/appointments/$publicId'
    | '/book/$serviceSlug'
    | '/checkout/$appointmentPublicId'
    | '/deities/$slug'
    | '/profile/consents'
    | '/profile/edit'
    | '/profile/spiritual'
    | '/sacred-houses/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/appointments/'
    | '/deities/'
    | '/payments/'
    | '/profile/'
    | '/sacred-houses/'
    | '/services/'
    | '/admin/appointments/$id'
    | '/admin/catalogue/review'
    | '/admin/payments/$id'
    | '/admin/prayer-templates/$id'
    | '/admin/prayer-templates/new'
    | '/admin/prayer-templates/review'
    | '/admin/sacred-content/$id'
    | '/admin/sacred-content/new'
    | '/admin/sacred-content/review'
    | '/admin/sacred-content/runtime'
    | '/admin/scheduling/$houseId'
    | '/admin/spiritual-content/$id'
    | '/admin/spiritual-content/new'
    | '/admin/spiritual-content/review'
    | '/api/webhooks/$provider'
    | '/payments/receipt/$attemptPublicId'
    | '/payments/return/$provider'
    | '/admin/appointments/'
    | '/admin/catalogue/'
    | '/admin/payments/'
    | '/admin/prayer-templates/'
    | '/admin/sacred-content/'
    | '/admin/scheduling/'
    | '/admin/spiritual-content/'
    | '/admin/catalogue/deities/$id'
    | '/admin/catalogue/deities/new'
    | '/admin/catalogue/sacred-houses/$id'
    | '/admin/catalogue/sacred-houses/new'
    | '/admin/catalogue/services/$id'
    | '/admin/catalogue/services/new'
    | '/admin/catalogue/deities/'
    | '/admin/catalogue/sacred-houses/'
    | '/admin/catalogue/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OlodumareRoute: typeof OlodumareRoute
  RegisterRoute: typeof RegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AppointmentsPublicIdRoute: typeof AppointmentsPublicIdRoute
  BookServiceSlugRoute: typeof BookServiceSlugRoute
  CheckoutAppointmentPublicIdRoute: typeof CheckoutAppointmentPublicIdRoute
  DeitiesSlugRoute: typeof DeitiesSlugRoute
  ProfileConsentsRoute: typeof ProfileConsentsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileSpiritualRoute: typeof ProfileSpiritualRoute
  SacredHousesSlugRoute: typeof SacredHousesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  DeitiesIndexRoute: typeof DeitiesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SacredHousesIndexRoute: typeof SacredHousesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiWebhooksProviderRoute: typeof ApiWebhooksProviderRoute
  PaymentsReceiptAttemptPublicIdRoute: typeof PaymentsReceiptAttemptPublicIdRoute
  PaymentsReturnProviderRoute: typeof PaymentsReturnProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olodumare': {
      id: '/olodumare'
      path: '/olodumare'
      fullPath: '/olodumare'
      preLoaderRoute: typeof OlodumareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$publicId': {
      id: '/appointments/$publicId'
      path: '/appointments/$publicId'
      fullPath: '/appointments/$publicId'
      preLoaderRoute: typeof AppointmentsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$serviceSlug': {
      id: '/book/$serviceSlug'
      path: '/book/$serviceSlug'
      fullPath: '/book/$serviceSlug'
      preLoaderRoute: typeof BookServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$appointmentPublicId': {
      id: '/checkout/$appointmentPublicId'
      path: '/checkout/$appointmentPublicId'
      fullPath: '/checkout/$appointmentPublicId'
      preLoaderRoute: typeof CheckoutAppointmentPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deities/': {
      id: '/deities/'
      path: '/deities'
      fullPath: '/deities/'
      preLoaderRoute: typeof DeitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deities/$slug': {
      id: '/deities/$slug'
      path: '/deities/$slug'
      fullPath: '/deities/$slug'
      preLoaderRoute: typeof DeitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/consents': {
      id: '/profile/consents'
      path: '/profile/consents'
      fullPath: '/profile/consents'
      preLoaderRoute: typeof ProfileConsentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/spiritual': {
      id: '/profile/spiritual'
      path: '/profile/spiritual'
      fullPath: '/profile/spiritual'
      preLoaderRoute: typeof ProfileSpiritualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacred-houses/': {
      id: '/sacred-houses/'
      path: '/sacred-houses'
      fullPath: '/sacred-houses/'
      preLoaderRoute: typeof SacredHousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacred-houses/$slug': {
      id: '/sacred-houses/$slug'
      path: '/sacred-houses/$slug'
      fullPath: '/sacred-houses/$slug'
      preLoaderRoute: typeof SacredHousesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/appointments'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/': {
      id: '/admin/catalogue/'
      path: '/catalogue'
      fullPath: '/admin/catalogue/'
      preLoaderRoute: typeof AdminCatalogueIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/review': {
      id: '/admin/catalogue/review'
      path: '/catalogue/review'
      fullPath: '/admin/catalogue/review'
      preLoaderRoute: typeof AdminCatalogueReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/payments/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer-templates/': {
      id: '/admin/prayer-templates/'
      path: '/prayer-templates'
      fullPath: '/admin/prayer-templates/'
      preLoaderRoute: typeof AdminPrayerTemplatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer-templates/$id': {
      id: '/admin/prayer-templates/$id'
      path: '/prayer-templates/$id'
      fullPath: '/admin/prayer-templates/$id'
      preLoaderRoute: typeof AdminPrayerTemplatesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer-templates/new': {
      id: '/admin/prayer-templates/new'
      path: '/prayer-templates/new'
      fullPath: '/admin/prayer-templates/new'
      preLoaderRoute: typeof AdminPrayerTemplatesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer-templates/review': {
      id: '/admin/prayer-templates/review'
      path: '/prayer-templates/review'
      fullPath: '/admin/prayer-templates/review'
      preLoaderRoute: typeof AdminPrayerTemplatesReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sacred-content/': {
      id: '/admin/sacred-content/'
      path: '/sacred-content'
      fullPath: '/admin/sacred-content/'
      preLoaderRoute: typeof AdminSacredContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sacred-content/$id': {
      id: '/admin/sacred-content/$id'
      path: '/sacred-content/$id'
      fullPath: '/admin/sacred-content/$id'
      preLoaderRoute: typeof AdminSacredContentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sacred-content/new': {
      id: '/admin/sacred-content/new'
      path: '/sacred-content/new'
      fullPath: '/admin/sacred-content/new'
      preLoaderRoute: typeof AdminSacredContentNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sacred-content/review': {
      id: '/admin/sacred-content/review'
      path: '/sacred-content/review'
      fullPath: '/admin/sacred-content/review'
      preLoaderRoute: typeof AdminSacredContentReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sacred-content/runtime': {
      id: '/admin/sacred-content/runtime'
      path: '/sacred-content/runtime'
      fullPath: '/admin/sacred-content/runtime'
      preLoaderRoute: typeof AdminSacredContentRuntimeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduling/': {
      id: '/admin/scheduling/'
      path: '/scheduling'
      fullPath: '/admin/scheduling/'
      preLoaderRoute: typeof AdminSchedulingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduling/$houseId': {
      id: '/admin/scheduling/$houseId'
      path: '/scheduling/$houseId'
      fullPath: '/admin/scheduling/$houseId'
      preLoaderRoute: typeof AdminSchedulingHouseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spiritual-content/': {
      id: '/admin/spiritual-content/'
      path: '/spiritual-content'
      fullPath: '/admin/spiritual-content/'
      preLoaderRoute: typeof AdminSpiritualContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spiritual-content/$id': {
      id: '/admin/spiritual-content/$id'
      path: '/spiritual-content/$id'
      fullPath: '/admin/spiritual-content/$id'
      preLoaderRoute: typeof AdminSpiritualContentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spiritual-content/new': {
      id: '/admin/spiritual-content/new'
      path: '/spiritual-content/new'
      fullPath: '/admin/spiritual-content/new'
      preLoaderRoute: typeof AdminSpiritualContentNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spiritual-content/review': {
      id: '/admin/spiritual-content/review'
      path: '/spiritual-content/review'
      fullPath: '/admin/spiritual-content/review'
      preLoaderRoute: typeof AdminSpiritualContentReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/$provider': {
      id: '/api/webhooks/$provider'
      path: '/api/webhooks/$provider'
      fullPath: '/api/webhooks/$provider'
      preLoaderRoute: typeof ApiWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/receipt/$attemptPublicId': {
      id: '/payments/receipt/$attemptPublicId'
      path: '/payments/receipt/$attemptPublicId'
      fullPath: '/payments/receipt/$attemptPublicId'
      preLoaderRoute: typeof PaymentsReceiptAttemptPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/return/$provider': {
      id: '/payments/return/$provider'
      path: '/payments/return/$provider'
      fullPath: '/payments/return/$provider'
      preLoaderRoute: typeof PaymentsReturnProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue/deities/': {
      id: '/admin/catalogue/deities/'
      path: '/catalogue/deities'
      fullPath: '/admin/catalogue/deities/'
      preLoaderRoute: typeof AdminCatalogueDeitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/deities/$id': {
      id: '/admin/catalogue/deities/$id'
      path: '/catalogue/deities/$id'
      fullPath: '/admin/catalogue/deities/$id'
      preLoaderRoute: typeof AdminCatalogueDeitiesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/deities/new': {
      id: '/admin/catalogue/deities/new'
      path: '/catalogue/deities/new'
      fullPath: '/admin/catalogue/deities/new'
      preLoaderRoute: typeof AdminCatalogueDeitiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/sacred-houses/': {
      id: '/admin/catalogue/sacred-houses/'
      path: '/catalogue/sacred-houses'
      fullPath: '/admin/catalogue/sacred-houses/'
      preLoaderRoute: typeof AdminCatalogueSacredHousesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/sacred-houses/$id': {
      id: '/admin/catalogue/sacred-houses/$id'
      path: '/catalogue/sacred-houses/$id'
      fullPath: '/admin/catalogue/sacred-houses/$id'
      preLoaderRoute: typeof AdminCatalogueSacredHousesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/sacred-houses/new': {
      id: '/admin/catalogue/sacred-houses/new'
      path: '/catalogue/sacred-houses/new'
      fullPath: '/admin/catalogue/sacred-houses/new'
      preLoaderRoute: typeof AdminCatalogueSacredHousesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/services/': {
      id: '/admin/catalogue/services/'
      path: '/catalogue/services'
      fullPath: '/admin/catalogue/services/'
      preLoaderRoute: typeof AdminCatalogueServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/services/$id': {
      id: '/admin/catalogue/services/$id'
      path: '/catalogue/services/$id'
      fullPath: '/admin/catalogue/services/$id'
      preLoaderRoute: typeof AdminCatalogueServicesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/services/new': {
      id: '/admin/catalogue/services/new'
      path: '/catalogue/services/new'
      fullPath: '/admin/catalogue/services/new'
      preLoaderRoute: typeof AdminCatalogueServicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
  AdminCatalogueReviewRoute: typeof AdminCatalogueReviewRoute
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
  AdminPrayerTemplatesIdRoute: typeof AdminPrayerTemplatesIdRoute
  AdminPrayerTemplatesNewRoute: typeof AdminPrayerTemplatesNewRoute
  AdminPrayerTemplatesReviewRoute: typeof AdminPrayerTemplatesReviewRoute
  AdminSacredContentIdRoute: typeof AdminSacredContentIdRoute
  AdminSacredContentNewRoute: typeof AdminSacredContentNewRoute
  AdminSacredContentReviewRoute: typeof AdminSacredContentReviewRoute
  AdminSacredContentRuntimeRoute: typeof AdminSacredContentRuntimeRoute
  AdminSchedulingHouseIdRoute: typeof AdminSchedulingHouseIdRoute
  AdminSpiritualContentIdRoute: typeof AdminSpiritualContentIdRoute
  AdminSpiritualContentNewRoute: typeof AdminSpiritualContentNewRoute
  AdminSpiritualContentReviewRoute: typeof AdminSpiritualContentReviewRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminCatalogueIndexRoute: typeof AdminCatalogueIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminPrayerTemplatesIndexRoute: typeof AdminPrayerTemplatesIndexRoute
  AdminSacredContentIndexRoute: typeof AdminSacredContentIndexRoute
  AdminSchedulingIndexRoute: typeof AdminSchedulingIndexRoute
  AdminSpiritualContentIndexRoute: typeof AdminSpiritualContentIndexRoute
  AdminCatalogueDeitiesIdRoute: typeof AdminCatalogueDeitiesIdRoute
  AdminCatalogueDeitiesNewRoute: typeof AdminCatalogueDeitiesNewRoute
  AdminCatalogueSacredHousesIdRoute: typeof AdminCatalogueSacredHousesIdRoute
  AdminCatalogueSacredHousesNewRoute: typeof AdminCatalogueSacredHousesNewRoute
  AdminCatalogueServicesIdRoute: typeof AdminCatalogueServicesIdRoute
  AdminCatalogueServicesNewRoute: typeof AdminCatalogueServicesNewRoute
  AdminCatalogueDeitiesIndexRoute: typeof AdminCatalogueDeitiesIndexRoute
  AdminCatalogueSacredHousesIndexRoute: typeof AdminCatalogueSacredHousesIndexRoute
  AdminCatalogueServicesIndexRoute: typeof AdminCatalogueServicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
  AdminCatalogueReviewRoute: AdminCatalogueReviewRoute,
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
  AdminPrayerTemplatesIdRoute: AdminPrayerTemplatesIdRoute,
  AdminPrayerTemplatesNewRoute: AdminPrayerTemplatesNewRoute,
  AdminPrayerTemplatesReviewRoute: AdminPrayerTemplatesReviewRoute,
  AdminSacredContentIdRoute: AdminSacredContentIdRoute,
  AdminSacredContentNewRoute: AdminSacredContentNewRoute,
  AdminSacredContentReviewRoute: AdminSacredContentReviewRoute,
  AdminSacredContentRuntimeRoute: AdminSacredContentRuntimeRoute,
  AdminSchedulingHouseIdRoute: AdminSchedulingHouseIdRoute,
  AdminSpiritualContentIdRoute: AdminSpiritualContentIdRoute,
  AdminSpiritualContentNewRoute: AdminSpiritualContentNewRoute,
  AdminSpiritualContentReviewRoute: AdminSpiritualContentReviewRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminCatalogueIndexRoute: AdminCatalogueIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminPrayerTemplatesIndexRoute: AdminPrayerTemplatesIndexRoute,
  AdminSacredContentIndexRoute: AdminSacredContentIndexRoute,
  AdminSchedulingIndexRoute: AdminSchedulingIndexRoute,
  AdminSpiritualContentIndexRoute: AdminSpiritualContentIndexRoute,
  AdminCatalogueDeitiesIdRoute: AdminCatalogueDeitiesIdRoute,
  AdminCatalogueDeitiesNewRoute: AdminCatalogueDeitiesNewRoute,
  AdminCatalogueSacredHousesIdRoute: AdminCatalogueSacredHousesIdRoute,
  AdminCatalogueSacredHousesNewRoute: AdminCatalogueSacredHousesNewRoute,
  AdminCatalogueServicesIdRoute: AdminCatalogueServicesIdRoute,
  AdminCatalogueServicesNewRoute: AdminCatalogueServicesNewRoute,
  AdminCatalogueDeitiesIndexRoute: AdminCatalogueDeitiesIndexRoute,
  AdminCatalogueSacredHousesIndexRoute: AdminCatalogueSacredHousesIndexRoute,
  AdminCatalogueServicesIndexRoute: AdminCatalogueServicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OlodumareRoute: OlodumareRoute,
  RegisterRoute: RegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  AppointmentsPublicIdRoute: AppointmentsPublicIdRoute,
  BookServiceSlugRoute: BookServiceSlugRoute,
  CheckoutAppointmentPublicIdRoute: CheckoutAppointmentPublicIdRoute,
  DeitiesSlugRoute: DeitiesSlugRoute,
  ProfileConsentsRoute: ProfileConsentsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileSpiritualRoute: ProfileSpiritualRoute,
  SacredHousesSlugRoute: SacredHousesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  DeitiesIndexRoute: DeitiesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SacredHousesIndexRoute: SacredHousesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiWebhooksProviderRoute: ApiWebhooksProviderRoute,
  PaymentsReceiptAttemptPublicIdRoute: PaymentsReceiptAttemptPublicIdRoute,
  PaymentsReturnProviderRoute: PaymentsReturnProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
