/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OlodumareRouteImport } from './routes/olodumare'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as DeitiesIndexRouteImport } from './routes/deities.index'
import { Route as DeitiesSlugRouteImport } from './routes/deities.$slug'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileConsentsRouteImport } from './routes/profile.consents'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileSpiritualRouteImport } from './routes/profile.spiritual'
import { Route as SacredHousesIndexRouteImport } from './routes/sacred-houses.index'
import { Route as SacredHousesSlugRouteImport } from './routes/sacred-houses.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin.appointments.index'
import { Route as AdminAppointmentsIdRouteImport } from './routes/admin.appointments.$id'
import { Route as AdminCatalogueIndexRouteImport } from './routes/admin.catalogue.index'
import { Route as AdminCatalogueReviewRouteImport } from './routes/admin.catalogue.review'
import { Route as AdminSchedulingIndexRouteImport } from './routes/admin.scheduling.index'
import { Route as AdminSchedulingHouseIdRouteImport } from './routes/admin.scheduling.$houseId'
import { Route as AdminCatalogueDeitiesIndexRouteImport } from './routes/admin.catalogue.deities.index'
import { Route as AdminCatalogueDeitiesIdRouteImport } from './routes/admin.catalogue.deities.$id'
import { Route as AdminCatalogueDeitiesNewRouteImport } from './routes/admin.catalogue.deities.new'
import { Route as AdminCatalogueSacredHousesIndexRouteImport } from './routes/admin.catalogue.sacred-houses.index'
import { Route as AdminCatalogueSacredHousesIdRouteImport } from './routes/admin.catalogue.sacred-houses.$id'
import { Route as AdminCatalogueSacredHousesNewRouteImport } from './routes/admin.catalogue.sacred-houses.new'
import { Route as AdminCatalogueServicesIndexRouteImport } from './routes/admin.catalogue.services.index'
import { Route as AdminCatalogueServicesIdRouteImport } from './routes/admin.catalogue.services.$id'
import { Route as AdminCatalogueServicesNewRouteImport } from './routes/admin.catalogue.services.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OlodumareRoute = OlodumareRouteImport.update({
  id: '/olodumare',
  path: '/olodumare',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DeitiesIndexRoute = DeitiesIndexRouteImport.update({
  id: '/deities/',
  path: '/deities/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeitiesSlugRoute = DeitiesSlugRouteImport.update({
  id: '/deities/$slug',
  path: '/deities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileConsentsRoute = ProfileConsentsRouteImport.update({
  id: '/profile/consents',
  path: '/profile/consents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSpiritualRoute = ProfileSpiritualRouteImport.update({
  id: '/profile/spiritual',
  path: '/profile/spiritual',
  getParentRoute: () => rootRouteImport,
} as any)
const SacredHousesIndexRoute = SacredHousesIndexRouteImport.update({
  id: '/sacred-houses/',
  path: '/sacred-houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const SacredHousesSlugRoute = SacredHousesSlugRouteImport.update({
  id: '/sacred-houses/$slug',
  path: '/sacred-houses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsIdRoute = AdminAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueIndexRoute = AdminCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueReviewRoute = AdminCatalogueReviewRouteImport.update({
  id: '/catalogue/review',
  path: '/catalogue/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulingIndexRoute = AdminSchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulingHouseIdRoute = AdminSchedulingHouseIdRouteImport.update({
  id: '/scheduling/$houseId',
  path: '/scheduling/$houseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueDeitiesIndexRoute =
  AdminCatalogueDeitiesIndexRouteImport.update({
    id: '/catalogue/deities/',
    path: '/catalogue/deities/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueDeitiesIdRoute = AdminCatalogueDeitiesIdRouteImport.update({
  id: '/catalogue/deities/$id',
  path: '/catalogue/deities/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueDeitiesNewRoute =
  AdminCatalogueDeitiesNewRouteImport.update({
    id: '/catalogue/deities/new',
    path: '/catalogue/deities/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueSacredHousesIndexRoute =
  AdminCatalogueSacredHousesIndexRouteImport.update({
    id: '/catalogue/sacred-houses/',
    path: '/catalogue/sacred-houses/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueSacredHousesIdRoute =
  AdminCatalogueSacredHousesIdRouteImport.update({
    id: '/catalogue/sacred-houses/$id',
    path: '/catalogue/sacred-houses/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueSacredHousesNewRoute =
  AdminCatalogueSacredHousesNewRouteImport.update({
    id: '/catalogue/sacred-houses/new',
    path: '/catalogue/sacred-houses/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueServicesIndexRoute =
  AdminCatalogueServicesIndexRouteImport.update({
    id: '/catalogue/services/',
    path: '/catalogue/services/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueServicesIdRoute =
  AdminCatalogueServicesIdRouteImport.update({
    id: '/catalogue/services/$id',
    path: '/catalogue/services/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogueServicesNewRoute =
  AdminCatalogueServicesNewRouteImport.update({
    id: '/catalogue/services/new',
    path: '/catalogue/services/new',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/olodumare': typeof OlodumareRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/deities/$slug': typeof DeitiesSlugRoute
  '/profile/consents': typeof ProfileConsentsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/spiritual': typeof ProfileSpiritualRoute
  '/sacred-houses/$slug': typeof SacredHousesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/deities/': typeof DeitiesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sacred-houses/': typeof SacredHousesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/catalogue/review': typeof AdminCatalogueReviewRoute
  '/admin/scheduling/$houseId': typeof AdminSchedulingHouseIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/catalogue/': typeof AdminCatalogueIndexRoute
  '/admin/scheduling/': typeof AdminSchedulingIndexRoute
  '/admin/catalogue/deities/$id': typeof AdminCatalogueDeitiesIdRoute
  '/admin/catalogue/deities/new': typeof AdminCatalogueDeitiesNewRoute
  '/admin/catalogue/sacred-houses/$id': typeof AdminCatalogueSacredHousesIdRoute
  '/admin/catalogue/sacred-houses/new': typeof AdminCatalogueSacredHousesNewRoute
  '/admin/catalogue/services/$id': typeof AdminCatalogueServicesIdRoute
  '/admin/catalogue/services/new': typeof AdminCatalogueServicesNewRoute
  '/admin/catalogue/deities/': typeof AdminCatalogueDeitiesIndexRoute
  '/admin/catalogue/sacred-houses/': typeof AdminCatalogueSacredHousesIndexRoute
  '/admin/catalogue/services/': typeof AdminCatalogueServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/olodumare': typeof OlodumareRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/deities/$slug': typeof DeitiesSlugRoute
  '/profile/consents': typeof ProfileConsentsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/spiritual': typeof ProfileSpiritualRoute
  '/sacred-houses/$slug': typeof SacredHousesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/deities': typeof DeitiesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/sacred-houses': typeof SacredHousesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/catalogue/review': typeof AdminCatalogueReviewRoute
  '/admin/scheduling/$houseId': typeof AdminSchedulingHouseIdRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/catalogue': typeof AdminCatalogueIndexRoute
  '/admin/scheduling': typeof AdminSchedulingIndexRoute
  '/admin/catalogue/deities/$id': typeof AdminCatalogueDeitiesIdRoute
  '/admin/catalogue/deities/new': typeof AdminCatalogueDeitiesNewRoute
  '/admin/catalogue/sacred-houses/$id': typeof AdminCatalogueSacredHousesIdRoute
  '/admin/catalogue/sacred-houses/new': typeof AdminCatalogueSacredHousesNewRoute
  '/admin/catalogue/services/$id': typeof AdminCatalogueServicesIdRoute
  '/admin/catalogue/services/new': typeof AdminCatalogueServicesNewRoute
  '/admin/catalogue/deities': typeof AdminCatalogueDeitiesIndexRoute
  '/admin/catalogue/sacred-houses': typeof AdminCatalogueSacredHousesIndexRoute
  '/admin/catalogue/services': typeof AdminCatalogueServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/olodumare': typeof OlodumareRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/deities/$slug': typeof DeitiesSlugRoute
  '/profile/consents': typeof ProfileConsentsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/spiritual': typeof ProfileSpiritualRoute
  '/sacred-houses/$slug': typeof SacredHousesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/deities/': typeof DeitiesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sacred-houses/': typeof SacredHousesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/catalogue/review': typeof AdminCatalogueReviewRoute
  '/admin/scheduling/$houseId': typeof AdminSchedulingHouseIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/catalogue/': typeof AdminCatalogueIndexRoute
  '/admin/scheduling/': typeof AdminSchedulingIndexRoute
  '/admin/catalogue/deities/$id': typeof AdminCatalogueDeitiesIdRoute
  '/admin/catalogue/deities/new': typeof AdminCatalogueDeitiesNewRoute
  '/admin/catalogue/sacred-houses/$id': typeof AdminCatalogueSacredHousesIdRoute
  '/admin/catalogue/sacred-houses/new': typeof AdminCatalogueSacredHousesNewRoute
  '/admin/catalogue/services/$id': typeof AdminCatalogueServicesIdRoute
  '/admin/catalogue/services/new': typeof AdminCatalogueServicesNewRoute
  '/admin/catalogue/deities/': typeof AdminCatalogueDeitiesIndexRoute
  '/admin/catalogue/sacred-houses/': typeof AdminCatalogueSacredHousesIndexRoute
  '/admin/catalogue/services/': typeof AdminCatalogueServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/olodumare'
    | '/register'
    | '/api/health'
    | '/deities/$slug'
    | '/profile/consents'
    | '/profile/edit'
    | '/profile/spiritual'
    | '/sacred-houses/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/deities/'
    | '/profile/'
    | '/sacred-houses/'
    | '/services/'
    | '/admin/appointments/$id'
    | '/admin/catalogue/review'
    | '/admin/scheduling/$houseId'
    | '/admin/appointments/'
    | '/admin/catalogue/'
    | '/admin/scheduling/'
    | '/admin/catalogue/deities/$id'
    | '/admin/catalogue/deities/new'
    | '/admin/catalogue/sacred-houses/$id'
    | '/admin/catalogue/sacred-houses/new'
    | '/admin/catalogue/services/$id'
    | '/admin/catalogue/services/new'
    | '/admin/catalogue/deities/'
    | '/admin/catalogue/sacred-houses/'
    | '/admin/catalogue/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/olodumare'
    | '/register'
    | '/api/health'
    | '/deities/$slug'
    | '/profile/consents'
    | '/profile/edit'
    | '/profile/spiritual'
    | '/sacred-houses/$slug'
    | '/services/$slug'
    | '/admin'
    | '/deities'
    | '/profile'
    | '/sacred-houses'
    | '/services'
    | '/admin/appointments/$id'
    | '/admin/catalogue/review'
    | '/admin/scheduling/$houseId'
    | '/admin/appointments'
    | '/admin/catalogue'
    | '/admin/scheduling'
    | '/admin/catalogue/deities/$id'
    | '/admin/catalogue/deities/new'
    | '/admin/catalogue/sacred-houses/$id'
    | '/admin/catalogue/sacred-houses/new'
    | '/admin/catalogue/services/$id'
    | '/admin/catalogue/services/new'
    | '/admin/catalogue/deities'
    | '/admin/catalogue/sacred-houses'
    | '/admin/catalogue/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/olodumare'
    | '/register'
    | '/api/health'
    | '/deities/$slug'
    | '/profile/consents'
    | '/profile/edit'
    | '/profile/spiritual'
    | '/sacred-houses/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/deities/'
    | '/profile/'
    | '/sacred-houses/'
    | '/services/'
    | '/admin/appointments/$id'
    | '/admin/catalogue/review'
    | '/admin/scheduling/$houseId'
    | '/admin/appointments/'
    | '/admin/catalogue/'
    | '/admin/scheduling/'
    | '/admin/catalogue/deities/$id'
    | '/admin/catalogue/deities/new'
    | '/admin/catalogue/sacred-houses/$id'
    | '/admin/catalogue/sacred-houses/new'
    | '/admin/catalogue/services/$id'
    | '/admin/catalogue/services/new'
    | '/admin/catalogue/deities/'
    | '/admin/catalogue/sacred-houses/'
    | '/admin/catalogue/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OlodumareRoute: typeof OlodumareRoute
  RegisterRoute: typeof RegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DeitiesSlugRoute: typeof DeitiesSlugRoute
  ProfileConsentsRoute: typeof ProfileConsentsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileSpiritualRoute: typeof ProfileSpiritualRoute
  SacredHousesSlugRoute: typeof SacredHousesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  DeitiesIndexRoute: typeof DeitiesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SacredHousesIndexRoute: typeof SacredHousesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olodumare': {
      id: '/olodumare'
      path: '/olodumare'
      fullPath: '/olodumare'
      preLoaderRoute: typeof OlodumareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deities/': {
      id: '/deities/'
      path: '/deities'
      fullPath: '/deities/'
      preLoaderRoute: typeof DeitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deities/$slug': {
      id: '/deities/$slug'
      path: '/deities/$slug'
      fullPath: '/deities/$slug'
      preLoaderRoute: typeof DeitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/consents': {
      id: '/profile/consents'
      path: '/profile/consents'
      fullPath: '/profile/consents'
      preLoaderRoute: typeof ProfileConsentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/spiritual': {
      id: '/profile/spiritual'
      path: '/profile/spiritual'
      fullPath: '/profile/spiritual'
      preLoaderRoute: typeof ProfileSpiritualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacred-houses/': {
      id: '/sacred-houses/'
      path: '/sacred-houses'
      fullPath: '/sacred-houses/'
      preLoaderRoute: typeof SacredHousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacred-houses/$slug': {
      id: '/sacred-houses/$slug'
      path: '/sacred-houses/$slug'
      fullPath: '/sacred-houses/$slug'
      preLoaderRoute: typeof SacredHousesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/appointments'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/': {
      id: '/admin/catalogue/'
      path: '/catalogue'
      fullPath: '/admin/catalogue/'
      preLoaderRoute: typeof AdminCatalogueIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/review': {
      id: '/admin/catalogue/review'
      path: '/catalogue/review'
      fullPath: '/admin/catalogue/review'
      preLoaderRoute: typeof AdminCatalogueReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduling/': {
      id: '/admin/scheduling/'
      path: '/scheduling'
      fullPath: '/admin/scheduling/'
      preLoaderRoute: typeof AdminSchedulingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduling/$houseId': {
      id: '/admin/scheduling/$houseId'
      path: '/scheduling/$houseId'
      fullPath: '/admin/scheduling/$houseId'
      preLoaderRoute: typeof AdminSchedulingHouseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/deities/': {
      id: '/admin/catalogue/deities/'
      path: '/catalogue/deities'
      fullPath: '/admin/catalogue/deities/'
      preLoaderRoute: typeof AdminCatalogueDeitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/deities/$id': {
      id: '/admin/catalogue/deities/$id'
      path: '/catalogue/deities/$id'
      fullPath: '/admin/catalogue/deities/$id'
      preLoaderRoute: typeof AdminCatalogueDeitiesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/deities/new': {
      id: '/admin/catalogue/deities/new'
      path: '/catalogue/deities/new'
      fullPath: '/admin/catalogue/deities/new'
      preLoaderRoute: typeof AdminCatalogueDeitiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/sacred-houses/': {
      id: '/admin/catalogue/sacred-houses/'
      path: '/catalogue/sacred-houses'
      fullPath: '/admin/catalogue/sacred-houses/'
      preLoaderRoute: typeof AdminCatalogueSacredHousesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/sacred-houses/$id': {
      id: '/admin/catalogue/sacred-houses/$id'
      path: '/catalogue/sacred-houses/$id'
      fullPath: '/admin/catalogue/sacred-houses/$id'
      preLoaderRoute: typeof AdminCatalogueSacredHousesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/sacred-houses/new': {
      id: '/admin/catalogue/sacred-houses/new'
      path: '/catalogue/sacred-houses/new'
      fullPath: '/admin/catalogue/sacred-houses/new'
      preLoaderRoute: typeof AdminCatalogueSacredHousesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/services/': {
      id: '/admin/catalogue/services/'
      path: '/catalogue/services'
      fullPath: '/admin/catalogue/services/'
      preLoaderRoute: typeof AdminCatalogueServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/services/$id': {
      id: '/admin/catalogue/services/$id'
      path: '/catalogue/services/$id'
      fullPath: '/admin/catalogue/services/$id'
      preLoaderRoute: typeof AdminCatalogueServicesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/services/new': {
      id: '/admin/catalogue/services/new'
      path: '/catalogue/services/new'
      fullPath: '/admin/catalogue/services/new'
      preLoaderRoute: typeof AdminCatalogueServicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
  AdminCatalogueReviewRoute: typeof AdminCatalogueReviewRoute
  AdminSchedulingHouseIdRoute: typeof AdminSchedulingHouseIdRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminCatalogueIndexRoute: typeof AdminCatalogueIndexRoute
  AdminSchedulingIndexRoute: typeof AdminSchedulingIndexRoute
  AdminCatalogueDeitiesIdRoute: typeof AdminCatalogueDeitiesIdRoute
  AdminCatalogueDeitiesNewRoute: typeof AdminCatalogueDeitiesNewRoute
  AdminCatalogueSacredHousesIdRoute: typeof AdminCatalogueSacredHousesIdRoute
  AdminCatalogueSacredHousesNewRoute: typeof AdminCatalogueSacredHousesNewRoute
  AdminCatalogueServicesIdRoute: typeof AdminCatalogueServicesIdRoute
  AdminCatalogueServicesNewRoute: typeof AdminCatalogueServicesNewRoute
  AdminCatalogueDeitiesIndexRoute: typeof AdminCatalogueDeitiesIndexRoute
  AdminCatalogueSacredHousesIndexRoute: typeof AdminCatalogueSacredHousesIndexRoute
  AdminCatalogueServicesIndexRoute: typeof AdminCatalogueServicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
  AdminCatalogueReviewRoute: AdminCatalogueReviewRoute,
  AdminSchedulingHouseIdRoute: AdminSchedulingHouseIdRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminCatalogueIndexRoute: AdminCatalogueIndexRoute,
  AdminSchedulingIndexRoute: AdminSchedulingIndexRoute,
  AdminCatalogueDeitiesIdRoute: AdminCatalogueDeitiesIdRoute,
  AdminCatalogueDeitiesNewRoute: AdminCatalogueDeitiesNewRoute,
  AdminCatalogueSacredHousesIdRoute: AdminCatalogueSacredHousesIdRoute,
  AdminCatalogueSacredHousesNewRoute: AdminCatalogueSacredHousesNewRoute,
  AdminCatalogueServicesIdRoute: AdminCatalogueServicesIdRoute,
  AdminCatalogueServicesNewRoute: AdminCatalogueServicesNewRoute,
  AdminCatalogueDeitiesIndexRoute: AdminCatalogueDeitiesIndexRoute,
  AdminCatalogueSacredHousesIndexRoute: AdminCatalogueSacredHousesIndexRoute,
  AdminCatalogueServicesIndexRoute: AdminCatalogueServicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OlodumareRoute: OlodumareRoute,
  RegisterRoute: RegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  DeitiesSlugRoute: DeitiesSlugRoute,
  ProfileConsentsRoute: ProfileConsentsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileSpiritualRoute: ProfileSpiritualRoute,
  SacredHousesSlugRoute: SacredHousesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  DeitiesIndexRoute: DeitiesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SacredHousesIndexRoute: SacredHousesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
